### PR TITLE
Bum Bum Tam Tam

### PR DESCRIPTION
**Pull request by Lebzul10**
"Ən uzun yaşayanlar Lerikdə yaşayanlardır"

### CODE REVIEW

**Comment by A1irzayevv** [comment]
What a perfect coding

**Review by huseynisrafilov17 — COMMENTED** [review]
You should have not deleted your peer's name.

**Comment by A1irzayevv** [comment]
Shame on Huseyn

**Comment by alirzayevhlbrtn** [comment]
Adimi yaz divara simpaticni avara

**Comment by isagarazadeh** [comment]
Can't see any gaps. Real example of peer learning be like this

**Comment by A1irzayevv** [comment]
> Can't see any gaps. Real example of peer learning be like this

very good point, we must be like hesen

**Pull request merged**
